[package]
name = "pulsecheck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.16.0"
crossterm = "0.22.0"
sysinfo = "0.30.7"
console = "0.15.8"